server:
  port: 8300

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  application:
    name: web-all
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
  elasticsearch:
    rest:
      uris: http://192.168.200.128:9200

# feign超时
feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000
  hystrix:
    enabled: true

