server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.200.128:3306/gmall_product?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  application:
    name: service-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
  redis:
    host: 192.168.200.128
    port: 6379
    database: 0


mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

nginx:
  fastdfs: http://192.168.200.128:8080

# feign超时
feign:
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000
