server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.200.128:3306/gmall_product?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

  mapper-locations: classpath:mapper/*Mapper.xml

nginx:
  fastdfs: http://192.168.200.128:8080